services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-7.0-latest
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: "zabbix-db"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
      POSTGRES_DB: "zabbix"
    depends_on:
      - zabbix-db
    restart: unless-stopped

  zabbix-db:
    image: postgres:16
    environment:
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
      POSTGRES_DB: "zabbix"
#    volumes:
#      - ./zabbix/db:/var/lib/postgresql/data
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-7.0-latest
    ports:
      - "8080:8080"
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      DB_SERVER_HOST: "zabbix-db"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
      POSTGRES_DB: "zabbix"
    depends_on:
      - zabbix-server
      - zabbix-db
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-7.0-latest
    privileged: true
    pid: "host"
    environment:
      ZBX_HOSTNAME: "WSL2-Host"
      ZBX_SERVER_HOST: "zabbix-server"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
#    volumes:
#      - ./grafana/data:/var/lib/grafana
    restart: unless-stopped
